#!/bin/zsh

applescript_code=$(cat << EOF
on WindowArrange(desired_position, desired_size)
	
	tell application "Finder" to set screen_size to bounds of window of desktop
	set screen_width to (item 3 of screen_size)
	set screen_height to ((item 4 of screen_size))
	
	set final_xsize to ((item 1 of desired_size) / 100) * screen_width
	set final_ysize to ((item 2 of desired_size) / 100) * screen_height
	
	set final_xpos to (((item 1 of desired_position) / 100) * screen_width)
	if (final_xpos + final_xsize) is greater than screen_width then
		set final_xpos to (screen_width - final_xsize)
	end if
	set final_ypos to (((item 2 of desired_position) / 100) * screen_height) + 44
	if (final_ypos + final_ysize) is greater than screen_height then
		set final_ysize to (screen_height - final_ypos)
	end if
	
	set final_pos to {final_xpos, final_ypos}
	set final_size to {final_xsize, final_ysize}
	
	set window_bounds to {final_pos} & {final_size}
	
	tell application "System Events" to tell front window of (first application process whose frontmost is true) to set {position, size} to window_bounds
end WindowArrange


on ClinicalVideos(desired_position, desired_size)
	set directory_path to POSIX file "/Users/diegoibarra/Media/Clinical"
	tell application "Finder"
		open directory_path
		activate
		my WindowArrange(desired_position, desired_size)
	end tell
end ClinicalVideos


on ClinicalVideosChecklist(desired_position, desired_size)
	set file_path to POSIX file "/Users/diegoibarra/Documents/School/OSU/Education/Step 2/Step2 Checklist.md"
	tell application "MarkEdit"
		open file_path
		delay 1
		activate
		my WindowArrange(desired_position, desired_size)
	end tell
end ClinicalVideosChecklist

on run
	-- ({X Pos, Y Pos}, {Width, Height})
	-- (Out of 100)
	
	my ClinicalVideos({75, 0}, {25, 36})
	my ClinicalVideosChecklist({75, 36}, {25, 64})
end run
EOF
)

osascript -e $applescript_code &