#!/bin/zsh

applescript_code=$(cat << EOF
on WindowArrange(desired_position, desired_size)
	
	tell application "Finder" to set screen_size to bounds of window of desktop
	set screen_width to (item 3 of screen_size)
	set screen_height to ((item 4 of screen_size))
	
	set final_xsize to ((item 1 of desired_size) / 100) * screen_width
	set final_ysize to ((item 2 of desired_size) / 100) * screen_height
	
	set final_xpos to (((item 1 of desired_position) / 100) * screen_width)
	if (final_xpos + final_xsize) is greater than screen_width then
		set final_xpos to (screen_width - final_xsize)
	end if
	set final_ypos to (((item 2 of desired_position) / 100) * screen_height) + 44
	if (final_ypos + final_ysize) is greater than screen_height then
		set final_ysize to (screen_height - final_ypos)
	end if
	
	set final_pos to {final_xpos, final_ypos}
	set final_size to {final_xsize, final_ysize}
	
	set window_bounds to {final_pos} & {final_size}
	
	tell application "System Events" to tell front window of (first application process whose frontmost is true) to set {position, size} to window_bounds
end WindowArrange


on Outlook(desired_position, desired_size)
	set app_name to "Microsoft Outlook"
	tell application app_name to activate
	
	tell application "System Events"
		set window_open to false
		repeat while window_open = false
			delay 1
			if (exists (window of process app_name)) then
				set window_open to true
			else
				tell application "System Events" to tell process app_name to click menu item 12 of menu 1 of menu item 1 of menu 3 of menu bar 1
			end if
		end repeat
	end tell
	my WindowArrange(desired_position, desired_size)
	
end Outlook

on ToDoList(desired_position, desired_size)
	set file_path to POSIX file "/Users/diegoibarra/Desktop/ToDo.md"
	tell application "MarkEdit"
		open file_path
		delay 1
		activate
		my WindowArrange(desired_position, desired_size)
	end tell
end ToDoList

on run
	-- ({X Pos, Y Pos}, {Width, Height})
	-- (Out of 100)
	
	my Outlook({0, 0}, {75, 100})
	my ToDoList({75, 0}, {25, 100})
end run
EOF
)

osascript -e $applescript_code &