#!/usr/bin/osascript

tell application "System Events"
  set window_pos to position of front window of (first application process whose frontmost is true)
  set original_X to item 1 of window_pos
  
  set finalPositionX to original_X
  set finalPositionY to 0
  set finalPosition to {finalPositionX, finalPositionY}
  
  tell front window of (first application process whose frontmost is true) to set {position} to {finalPosition}
end tell