#!/usr/bin/osascript

tell application "System Events"
	tell application "Finder" to set screen_size to bounds of window of desktop
	set _WINDOW to front window of (first application process whose frontmost is true)
	set window_pos to position of _WINDOW
	set window_size to size of _WINDOW
	set finalPositionX to ((item 3 of screen_size) - (item 1 of window_size))
	set finalPosition to {finalPositionX, item 2 of window_pos}
	tell _WINDOW to set {position} to {finalPosition}
end tell