#!/usr/bin/osascript

tell application "System Events"
  set window_pos to position of front window of (first application process whose frontmost is true)
  set original_Y to item 2 of window_pos
  
  set finalPositionX to 0
  set finalPositionY to original_Y
  set finalPosition to {finalPositionX, finalPositionY}
  
  tell front window of (first application process whose frontmost is true) to set {position} to {finalPosition}
end tell