#!/usr/bin/osascript

on run ()
	
	log "--------START OF ADMINAPPROVAL_SCPT---------"	
	set process_name to "SecurityAgent"
	set window_counter to 0
	set process_counter to 0

	repeat until isRunning(process_name) is true
		set process_counter to (process_counter + 1)
		log "Finding Process: " & (process_counter as string)
		if process_counter is greater than 300
			log "SelfControl Process NOT found"
			error number -128
		end if
		delay 0.01
	end repeat
	log "SelfControl Process IS Running"


	tell application "System Events" to tell process "SecurityAgent"
		repeat until exists text field 1 of window 1
			set window_counter to (window_counter + 1)
			log "Finding Window: " & (window_counter as string)
			if window_counter is greater than 300 
				log "SecurityAgent Window NOT found"
				error number -128
			end if
			delay 0.01
		end repeat

		set value of text field 1 of window 1 to "Diego Ibarra"
		set value of text field 2 of window 1 to "hahahey"
		
		log "Clicking OK button"
		delay 5
		click button "OK" of window 1
	end tell
end run

on isRunning(process_or_app)
	tell application "System Events" to (name of processes) contains process_or_app
end isRunning
