#!/bin/zsh

SELFCONTROL_CLI="/Applications/SelfControl.app/Contents/MacOS/selfcontrol-cli"

WORK_DIR="/Users/diegoibarra/Developer/1_myProjects/MiniProjects/AutoSelfControl"
RESOURCE_DIR="${WORK_DIR}/Resources"
BLOCKLIST_FILE="${RESOURCE_DIR}/blocklist_entertainment.selfcontrol"

# START_DATE=$(./endDate.py 1)
END_DATE=$(./endDate.py 2)

cd $WORK_DIR

# echo $START_DATE
# echo $END_DATE

./AdminApproval_scpt &
sudo $SELFCONTROL_CLI --uid 501 start --blocklist $BLOCKLIST_FILE --enddate $END_DATE > /dev/null 2>&1
